"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k90!a!j)fsal#$0a#13r%5bv#29yxb%(i7f&3o+r*)f=$=0=y_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django_filters',
    'widget_tweaks', # для изменения форм
    # убрали 'news' так как добавили сигнал
    'sign',
    'protect',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # ... include the providers you want to enable:
    'allauth.socialaccount.providers.google',

    # Module D6.4
    # надо указать не имя нашего приложения, а его конфиг, чтобы всё заработало
    'news.apps.NewsConfig',
    # Module D6.5
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

SITE_ID = 1

ROOT_URLCONF = 'NewsPaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# стартовая страница при запуске сервера
LOGIN_URL = '/sign/login/'
# переход после авторизации/входа пользователя 
LOGIN_REDIRECT_URL = '/news'


ACCOUNT_FORMS = {'signup': 'sign.models.CommonSignupForm'}



ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False


ACCOUNT_AUTHENTICATION_METHOD = 'email'
# для проверки и подтверждения почты по переходу/ без неё не сработает
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

WSGI_APPLICATION = 'NewsPaper.wsgi.application'

# дополнительные настройки для подтверждения почты
# ACCOUNT_CONFIRM_EMAIL_ON_GET = True - позволит избежать дополнительных действий и активирует аккаунт сразу, как только мы перейдём по ссылке
# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS - количество дней, в течение которых будет доступна ссылка на подтверждение регистрации и так далее


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-EN'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Module D6.2
# smtp yandex -> другие программы -> настройте ящик -> первые две галки во всех пунктах
EMAIL_HOST = 'smtp.yandex.ru' # адрес сервера Яндекс-почты для всех один и тот же
EMAIL_PORT = 465 # порт smtp сервера тоже одинаковый
EMAIL_HOST_USER = '' # ваше имя пользователя, например если ваша почта user@yandex.ru, то сюда надо писать user, иными словами, это всё то что идёт до собаки
EMAIL_HOST_PASSWORD = '' # пароль от почты
EMAIL_USE_SSL = True # Яндекс использует ssl, подробнее о том, что это, почитайте на Википедии, но включать его здесь обязательно


# Module D6.3
DEFAULT_FROM_EMAIL = '' # здесь указываем уже свою ПОЛНУЮ почту с которой будут отправляться письма

# изменяем настройки так, как это было в документации
# https://django-allauth.readthedocs.io/en/latest/installation.html

# Module D6.5

# формат даты, которую будет воспринимать наш задачник(вспоминаем урок по фильтрам)
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

# если задача не выполняется за 25 секунд, то она автоматически снимается, можете поставить время побольше,
# но как правило, это сильно бьёт по производительности сервера
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'), # Указываем, куда будем сохранять кэшируемые файлы! Не забываем создать папку cache_files внутри папки с manage.py!
    }
}

# Словарь конфигурации логирования
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # Форматы выдаваемых сообщений
    'formatters': {
        # Debug и выше, (уровень, время, сообщение)
        'base_format': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
        # Warning и выше (включает путь к источнику события pathname)
        'warning_format': {
            'format': '%(levelname)s %(asctime)s %(pathname)s %(message)s'
        },
        # Error и Critical, файл errors.log (содержит стек ошибок exc_info)
        'error_format': {
            'format': '%(levelname)s %(asctime)s %(pathname)s %(exc_info)s %(message)s'
        },
        # general.log (время, уровень, название модуля)
        'general_format': {
            'format': '%(levelname)s %(asctime)s %(module)s'
        },
        # security.log (время, уровень, название модуля, сообщение)
        'security_format': {
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s'
        }
    },
    # Фильтры. В консоль сообщения отправляются только при DEBUG = True, а на почту и в файл general.log — только при DEBUG = False.
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    # Обработчики сообщений, вывод по флагам, в консоль и/или log файл.
    'handlers': {
        # Debug и выше (если Debug = true)
        'base_console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'base_format'
        },
        # Warning и выше (если Debug = true)
        'warning_console': {
            'level': 'WARNING',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'warning_format'
        },
        # Error и выше (если Debug = true)
        'error_console': {
            'level': 'ERROR',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'error_format'
        },
        # Info и выше
        'general_log_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'general.log'),
            'formatter': 'general_format'
        },
        # Error и выше
        'error_log_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'errors.log'),
            'formatter': 'error_format'
        },
        # security.log
        'security_log_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'security.log'),
            'formatter': 'security_format'
        },
        # Error и выше (если Debug = false)
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'warning_format'
        }
    },
    # Выделение сообщений логгера django
    'loggers': {
        # Вывод всех сообщений в консоль и запись в general.log от django
        'django': {
            'handlers': ['base_console', 'warning_console', 'error_console', 'general_log_file'],
            'propagate': True,
        },
        # Запись в errors.log и отправка по почте сообщений от django.request
        'django.request': {
            'handlers': ['error_log_file', 'mail_admins'],
            'propagate': False,
        },
        # Запись в errors.log и отправка по почте сообщений от django.server
        'django.server': {
            'handlers': ['error_log_file', 'mail_admins'],
            'propagate': False,
        },
        # Запись в errors.log сообщений от django.template
        'django.template': {
            'handlers': ['error_log_file'],
            'propagate': False,
        },
        # Запись в errors.log сообщений от django.db_backends
        'django.db_backends': {
            'handlers': ['error_log_file'],
            'propagate': False,
        },
        # Запись в security.log сообщений от django.security
        'django.security': {
            'handlers': ['security_log_file'],
            'propagate': False,
        },
    }

}