# Generated by Django 4.1.7 on 2023-03-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_category_subscribers_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('N', 'News'), ('A', 'Articles')], default='N', max_length=1),
        ),
    ]
